spring.application.name=ai-careos-backend

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/ai_careeros}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false

server.port=${PORT:8080}
